### This is the docker-compose development file.
### So far, the frontend and the database both load properly, but the server can't connect to the database.

version: '3.8'

services:
  frontend:
    container_name: blog_frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    command: ["npm", "start"]
    depends_on: 
      - server
  server:
    container_name: blog_server
    build:
      context: ./server
    # volumes:
    #   - ./server:/usr/src/app
    ports:  
      - 5000:5000
    # This script executes with respect to where it is in the container filesystem.
    # ["./wait-for.sh", "db:3306", "nodemon", "server.js"]
    command: >
      sh -c "
        ./wait-for.sh db:3306 &&
        nodemon server.js
      "
    depends_on:
      - db
    env_file:
      - server/config.env
  db:
    container_name: blog_db
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # This allows us to initialize a database from a dump on container load.
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3307:3306
    restart: always
    cap_add:
      - SYS_NICE
    env_file:
      - database/db.env