### This is the docker-compose development file.

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    command: ["npm", "start"]
    depends_on: 
      - server
  server:
    build:
      context: ./server
    # volumes:
    #   - ./server:/usr/src/app
    ports:  
      - 5000:5000
    command: ["nodemon", "server.js"]
    env_file:
      - server/config.env