### This is the docker-compose development file.

version: '3.8'

services:
  website:
    container_name: main_website
    build:
      context: ./my_website
    volumes:
      - ./my_website:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    restart: always
    command: ["npm", "run", "dev"]
    depends_on:
      - db
    env_file: 
      - my_website/config.env

  frontend:
    container_name: blog_frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: ["npm", "start"]
    depends_on: 
      - server

  server:
    container_name: blog_server
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:  
      - 5000:5000
    restart: always
    command: >
      sh -c "nodemon server.js"
    depends_on:
      - db
    env_file:
      - server/config.env

  db:
    container_name: blog_db
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # This allows us to initialize a database from a dump on container load.
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3307:3306
    restart: always
    cap_add:
      - SYS_NICE
    security_opt: 
      - seccomp:unconfined
    env_file:
      - database/db.env